export const DEFAULT_SITE_NAME = 'OwnAPI'
export const DEFAULT_SITE_SUBTITLE = 'OwnAPI'
export const DEFAULT_PAYMENT_PRODUCT_PREFIX = DEFAULT_SITE_NAME
export const DEFAULT_DOC_URL = ''
export const DEFAULT_REPOSITORY_URL = ''
